config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root to: 'employee#index'

  get '/search' => 'employee#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
    require 'rest-client'
    require 'excon'
    require 'json'
    require 'ostruct'

    def index
    end
  
    def search
      employees = find_employee(params[:employee])
      @employee = employees
      unless employees
        flash[:alert] = 'Employee not found'
        return render action: :index
      end
      # ...
    end
  
    # app/controllers/travel_controller.rb
    private
  
   

    # def request_api(url)
    #   response = RestClient.get(url)
    #   print("response: ", response)
    #   object = JSON.parse(response, object_class: OpenStruct)
    #   print(object._embedded.employeeList)
    #   JSON.parse(object.toString())
    # end

    def request_api(url)
      begin
        response = RestClient.get(url)
        print("response: ", response)
        JSON.parse(response)
      rescue
         return nil
      end
  
      
    end
  
    def find_employee(id)
      request_api(
        "http://localhost:8080/employees/#{URI.encode(id)}"
      )
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employee/index.html.erb
<!-- app/views/records/index.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <% if flash[:alert] %>
        <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :country, 'Search for an employee '%>
            <%= text_field_tag :employee, nil, placeholder: 'Eg. 1', class: 'form-control' %>
          </div>

          <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/employee/search.html.erb
<!-- app/views/travel/search.html.erb -->
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>Employee info</h4>
      
      <table class="table">
  <thead>
    <tr>
      <th scope="col">Employee ID</th>
      <th scope="col">Name</th>
      <th scope="col">Role</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @employee['id'] %></td>
      <td><%= @employee['name'] %></td>
      <td><%= @employee['role'] %></td>
    </tr>
  </tbody>
</table>


    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>